### ISSUE TITLE
tensorflow-gpu in requirements.txt?

### ISSUE THREAD

**Issue by ivenzor** [udacity/deep-reinforcement-learning#1]
I changed my local requirements.txt to include tensorflow-gpu==1.7.1 because "pip install ." tried to download/install non gpu tensorflow but tensorflow-gpu==1.7.1 was already installed.

Maybe the requirements.txt can change to include tensorflow-gpu==1.7.1 ?

**Comment by alexisbcook** [comment]
Thanks for raising! Currently, it's better to leave the requirement as tensorflow (instead of tensorflow-gpu), since (1) tensorflow-gpu won't work on mac, and (2) all of the exercises that could benefit from GPU acceleration in the DRLND will be completed in pytorch.

(_We decided to leave tensorflow as a requirement, in case students want to further explore the [cool capabilities of the ML-Agents toolkit](https://blogs.unity3d.com/2018/06/19/unity-ml-agents-toolkit-v0-4-and-udacity-deep-reinforcement-learning-nanodegree/) ... in this case, your Python installation is ready to go!_)
